### ISSUE TITLE
Hope you give a complete example, there are some several problems.

### ISSUE THREAD

**Issue by minglinlu** [github-pengge/Image_retrieval#1]
Traceback (most recent call last):
  File "extract_descriptors.py", line 29, in <module>
    response = voc.sims(descriptor)  # response is a list of image ids of training images.
  File "/Users/lml/Desktop/Image_retrieval/vocabulary.py", line 90, in sims
    for im_id in node.get_additional_data():
AttributeError: 'list' object has no attribute 'get_additional_data'

**Comment by gapeng000** [comment]
I believe that in your `extract_descriptors.py` file, you did not build a vocabulary tree using the correct api. There's an example(see step 2) in [readme](https://github.com/github-pengge/Image_retrieval/blob/master/README.md).

**Comment by minglinlu** [comment]
I did build the vocabulary tree according to your step 1~3, the code is just the same as it. When I change the descriptor to descriptors[0] generated in step 1, there is another issue, im_sims.get(im_id[0], im_id[1]) is inf, T T. I'm using opencv 2.4.13 and python 2.7 on mac os x.
